// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/user.proto

package helloworld

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchRequest_Corpus int32

const (
	SearchRequest_UNIVERSAL SearchRequest_Corpus = 0
	SearchRequest_WEB       SearchRequest_Corpus = 1
	SearchRequest_IMAGES    SearchRequest_Corpus = 2
)

var SearchRequest_Corpus_name = map[int32]string{
	0: "UNIVERSAL",
	1: "WEB",
	2: "IMAGES",
}

var SearchRequest_Corpus_value = map[string]int32{
	"UNIVERSAL": 0,
	"WEB":       1,
	"IMAGES":    2,
}

func (x SearchRequest_Corpus) String() string {
	return proto.EnumName(SearchRequest_Corpus_name, int32(x))
}

func (SearchRequest_Corpus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{12, 0}
}

type UserByUIDRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserByUIDRequest) Reset()         { *m = UserByUIDRequest{} }
func (m *UserByUIDRequest) String() string { return proto.CompactTextString(m) }
func (*UserByUIDRequest) ProtoMessage()    {}
func (*UserByUIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{0}
}

func (m *UserByUIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserByUIDRequest.Unmarshal(m, b)
}
func (m *UserByUIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserByUIDRequest.Marshal(b, m, deterministic)
}
func (m *UserByUIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserByUIDRequest.Merge(m, src)
}
func (m *UserByUIDRequest) XXX_Size() int {
	return xxx_messageInfo_UserByUIDRequest.Size(m)
}
func (m *UserByUIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserByUIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserByUIDRequest proto.InternalMessageInfo

func (m *UserByUIDRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type UserByUIDReply struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	UserRole             *UserRole `protobuf:"bytes,2,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserByUIDReply) Reset()         { *m = UserByUIDReply{} }
func (m *UserByUIDReply) String() string { return proto.CompactTextString(m) }
func (*UserByUIDReply) ProtoMessage()    {}
func (*UserByUIDReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{1}
}

func (m *UserByUIDReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserByUIDReply.Unmarshal(m, b)
}
func (m *UserByUIDReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserByUIDReply.Marshal(b, m, deterministic)
}
func (m *UserByUIDReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserByUIDReply.Merge(m, src)
}
func (m *UserByUIDReply) XXX_Size() int {
	return xxx_messageInfo_UserByUIDReply.Size(m)
}
func (m *UserByUIDReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserByUIDReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserByUIDReply proto.InternalMessageInfo

func (m *UserByUIDReply) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserByUIDReply) GetUserRole() *UserRole {
	if m != nil {
		return m.UserRole
	}
	return nil
}

type UserInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId             string   `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Level                uint64   `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Energy               uint64   `protobuf:"varint,4,opt,name=energy,proto3" json:"energy,omitempty"`
	AppUid               uint64   `protobuf:"varint,5,opt,name=app_uid,json=appUid,proto3" json:"app_uid,omitempty"`
	Nickname             string   `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar               string   `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Age                  int32    `protobuf:"varint,8,opt,name=age,proto3" json:"age,omitempty"`
	Sex                  int32    `protobuf:"varint,9,opt,name=sex,proto3" json:"sex,omitempty"`
	Profile              string   `protobuf:"bytes,10,opt,name=profile,proto3" json:"profile,omitempty"`
	Country              int64    `protobuf:"varint,11,opt,name=country,proto3" json:"country,omitempty"`
	City                 string   `protobuf:"bytes,12,opt,name=city,proto3" json:"city,omitempty"`
	Count                uint64   `protobuf:"varint,13,opt,name=count,proto3" json:"count,omitempty"`
	NewGuidance          uint64   `protobuf:"varint,14,opt,name=new_guidance,json=newGuidance,proto3" json:"new_guidance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{2}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserInfo) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *UserInfo) GetLevel() uint64 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *UserInfo) GetEnergy() uint64 {
	if m != nil {
		return m.Energy
	}
	return 0
}

func (m *UserInfo) GetAppUid() uint64 {
	if m != nil {
		return m.AppUid
	}
	return 0
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *UserInfo) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *UserInfo) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func (m *UserInfo) GetCountry() int64 {
	if m != nil {
		return m.Country
	}
	return 0
}

func (m *UserInfo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *UserInfo) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *UserInfo) GetNewGuidance() uint64 {
	if m != nil {
		return m.NewGuidance
	}
	return 0
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ClientDate           uint64   `protobuf:"varint,2,opt,name=client_date,json=clientDate,proto3" json:"client_date,omitempty"`
	DeviceNew            string   `protobuf:"bytes,3,opt,name=device_new,json=deviceNew,proto3" json:"device_new,omitempty"`
	Platform             string   `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Version              string   `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Device               string   `protobuf:"bytes,7,opt,name=device,proto3" json:"device,omitempty"`
	GameDeviceId         string   `protobuf:"bytes,8,opt,name=game_device_id,json=gameDeviceId,proto3" json:"game_device_id,omitempty"`
	Country              int64    `protobuf:"varint,9,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetClientDate() uint64 {
	if m != nil {
		return m.ClientDate
	}
	return 0
}

func (m *LoginRequest) GetDeviceNew() string {
	if m != nil {
		return m.DeviceNew
	}
	return ""
}

func (m *LoginRequest) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *LoginRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *LoginRequest) GetGameDeviceId() string {
	if m != nil {
		return m.GameDeviceId
	}
	return ""
}

func (m *LoginRequest) GetCountry() int64 {
	if m != nil {
		return m.Country
	}
	return 0
}

type LoginReply struct {
	Uid                  string          `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	AppUid               uint64          `protobuf:"varint,2,opt,name=app_uid,json=appUid,proto3" json:"app_uid,omitempty"`
	UserRole             *UserRole       `protobuf:"bytes,3,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`
	WearingEquip         *EquipResp      `protobuf:"bytes,4,opt,name=wearing_equip,json=wearingEquip,proto3" json:"wearing_equip,omitempty"`
	EquipList            []*ShopItemInfo `protobuf:"bytes,5,rep,name=equip_list,json=equipList,proto3" json:"equip_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{4}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LoginReply) GetAppUid() uint64 {
	if m != nil {
		return m.AppUid
	}
	return 0
}

func (m *LoginReply) GetUserRole() *UserRole {
	if m != nil {
		return m.UserRole
	}
	return nil
}

func (m *LoginReply) GetWearingEquip() *EquipResp {
	if m != nil {
		return m.WearingEquip
	}
	return nil
}

func (m *LoginReply) GetEquipList() []*ShopItemInfo {
	if m != nil {
		return m.EquipList
	}
	return nil
}

type ShopItemInfo struct {
	ItemId               int64    `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Price                int64    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	IsBuy                bool     `protobuf:"varint,3,opt,name=is_buy,json=isBuy,proto3" json:"is_buy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopItemInfo) Reset()         { *m = ShopItemInfo{} }
func (m *ShopItemInfo) String() string { return proto.CompactTextString(m) }
func (*ShopItemInfo) ProtoMessage()    {}
func (*ShopItemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{5}
}

func (m *ShopItemInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopItemInfo.Unmarshal(m, b)
}
func (m *ShopItemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopItemInfo.Marshal(b, m, deterministic)
}
func (m *ShopItemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopItemInfo.Merge(m, src)
}
func (m *ShopItemInfo) XXX_Size() int {
	return xxx_messageInfo_ShopItemInfo.Size(m)
}
func (m *ShopItemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopItemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ShopItemInfo proto.InternalMessageInfo

func (m *ShopItemInfo) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *ShopItemInfo) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ShopItemInfo) GetIsBuy() bool {
	if m != nil {
		return m.IsBuy
	}
	return false
}

// 返回得装备信息列表
type EquipResp struct {
	EquipList            []*EquipInfo `protobuf:"bytes,1,rep,name=equip_list,json=equipList,proto3" json:"equip_list,omitempty"`
	PlastommerId         uint64       `protobuf:"varint,2,opt,name=plastommer_id,json=plastommerId,proto3" json:"plastommer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EquipResp) Reset()         { *m = EquipResp{} }
func (m *EquipResp) String() string { return proto.CompactTextString(m) }
func (*EquipResp) ProtoMessage()    {}
func (*EquipResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{6}
}

func (m *EquipResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EquipResp.Unmarshal(m, b)
}
func (m *EquipResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EquipResp.Marshal(b, m, deterministic)
}
func (m *EquipResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EquipResp.Merge(m, src)
}
func (m *EquipResp) XXX_Size() int {
	return xxx_messageInfo_EquipResp.Size(m)
}
func (m *EquipResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EquipResp.DiscardUnknown(m)
}

var xxx_messageInfo_EquipResp proto.InternalMessageInfo

func (m *EquipResp) GetEquipList() []*EquipInfo {
	if m != nil {
		return m.EquipList
	}
	return nil
}

func (m *EquipResp) GetPlastommerId() uint64 {
	if m != nil {
		return m.PlastommerId
	}
	return 0
}

// 一件装备的详细信息
type EquipInfo struct {
	ItemType             int64    `protobuf:"varint,1,opt,name=itemType,proto3" json:"itemType,omitempty"`
	ItemID               int64    `protobuf:"varint,2,opt,name=itemID,proto3" json:"itemID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EquipInfo) Reset()         { *m = EquipInfo{} }
func (m *EquipInfo) String() string { return proto.CompactTextString(m) }
func (*EquipInfo) ProtoMessage()    {}
func (*EquipInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{7}
}

func (m *EquipInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EquipInfo.Unmarshal(m, b)
}
func (m *EquipInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EquipInfo.Marshal(b, m, deterministic)
}
func (m *EquipInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EquipInfo.Merge(m, src)
}
func (m *EquipInfo) XXX_Size() int {
	return xxx_messageInfo_EquipInfo.Size(m)
}
func (m *EquipInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EquipInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EquipInfo proto.InternalMessageInfo

func (m *EquipInfo) GetItemType() int64 {
	if m != nil {
		return m.ItemType
	}
	return 0
}

func (m *EquipInfo) GetItemID() int64 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

type UserRole struct {
	EmotionId            uint64   `protobuf:"varint,1,opt,name=emotion_id,json=emotionId,proto3" json:"emotion_id,omitempty"`
	ModelId              uint64   `protobuf:"varint,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRole) Reset()         { *m = UserRole{} }
func (m *UserRole) String() string { return proto.CompactTextString(m) }
func (*UserRole) ProtoMessage()    {}
func (*UserRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{8}
}

func (m *UserRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRole.Unmarshal(m, b)
}
func (m *UserRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRole.Marshal(b, m, deterministic)
}
func (m *UserRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRole.Merge(m, src)
}
func (m *UserRole) XXX_Size() int {
	return xxx_messageInfo_UserRole.Size(m)
}
func (m *UserRole) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRole.DiscardUnknown(m)
}

var xxx_messageInfo_UserRole proto.InternalMessageInfo

func (m *UserRole) GetEmotionId() uint64 {
	if m != nil {
		return m.EmotionId
	}
	return 0
}

func (m *UserRole) GetModelId() uint64 {
	if m != nil {
		return m.ModelId
	}
	return 0
}

type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Country              int32    `protobuf:"varint,3,opt,name=country,proto3" json:"country,omitempty"`
	PhoneNum             string   `protobuf:"bytes,4,opt,name=phone_num,json=phoneNum,proto3" json:"phone_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{9}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetCountry() int32 {
	if m != nil {
		return m.Country
	}
	return 0
}

func (m *RegisterRequest) GetPhoneNum() string {
	if m != nil {
		return m.PhoneNum
	}
	return ""
}

type RegisterReply struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReply) Reset()         { *m = RegisterReply{} }
func (m *RegisterReply) String() string { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()    {}
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{10}
}

func (m *RegisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReply.Unmarshal(m, b)
}
func (m *RegisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReply.Marshal(b, m, deterministic)
}
func (m *RegisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReply.Merge(m, src)
}
func (m *RegisterReply) XXX_Size() int {
	return xxx_messageInfo_RegisterReply.Size(m)
}
func (m *RegisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReply proto.InternalMessageInfo

func (m *RegisterReply) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type Profile struct {
	// Types that are valid to be assigned to Avatar:
	//	*Profile_ImageUrl
	//	*Profile_ImageData
	Avatar               isProfile_Avatar `protobuf_oneof:"avatar"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{11}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

type isProfile_Avatar interface {
	isProfile_Avatar()
}

type Profile_ImageUrl struct {
	ImageUrl string `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3,oneof"`
}

type Profile_ImageData struct {
	ImageData []byte `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3,oneof"`
}

func (*Profile_ImageUrl) isProfile_Avatar() {}

func (*Profile_ImageData) isProfile_Avatar() {}

func (m *Profile) GetAvatar() isProfile_Avatar {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *Profile) GetImageUrl() string {
	if x, ok := m.GetAvatar().(*Profile_ImageUrl); ok {
		return x.ImageUrl
	}
	return ""
}

func (m *Profile) GetImageData() []byte {
	if x, ok := m.GetAvatar().(*Profile_ImageData); ok {
		return x.ImageData
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Profile) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Profile_ImageUrl)(nil),
		(*Profile_ImageData)(nil),
	}
}

//  演示  key:value----> int32:map[int32]int32
type SearchRequest struct {
	Corpus               SearchRequest_Corpus `protobuf:"varint,1,opt,name=corpus,proto3,enum=helloworld.SearchRequest_Corpus" json:"corpus,omitempty"`
	List                 map[int32]*ListDate  `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{12}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetCorpus() SearchRequest_Corpus {
	if m != nil {
		return m.Corpus
	}
	return SearchRequest_UNIVERSAL
}

func (m *SearchRequest) GetList() map[int32]*ListDate {
	if m != nil {
		return m.List
	}
	return nil
}

type ListDate struct {
	List                 map[int32]int32 `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListDate) Reset()         { *m = ListDate{} }
func (m *ListDate) String() string { return proto.CompactTextString(m) }
func (*ListDate) ProtoMessage()    {}
func (*ListDate) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4f917211a932270, []int{13}
}

func (m *ListDate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDate.Unmarshal(m, b)
}
func (m *ListDate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDate.Marshal(b, m, deterministic)
}
func (m *ListDate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDate.Merge(m, src)
}
func (m *ListDate) XXX_Size() int {
	return xxx_messageInfo_ListDate.Size(m)
}
func (m *ListDate) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDate.DiscardUnknown(m)
}

var xxx_messageInfo_ListDate proto.InternalMessageInfo

func (m *ListDate) GetList() map[int32]int32 {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterEnum("helloworld.SearchRequest_Corpus", SearchRequest_Corpus_name, SearchRequest_Corpus_value)
	proto.RegisterType((*UserByUIDRequest)(nil), "helloworld.UserByUIDRequest")
	proto.RegisterType((*UserByUIDReply)(nil), "helloworld.UserByUIDReply")
	proto.RegisterType((*UserInfo)(nil), "helloworld.UserInfo")
	proto.RegisterType((*LoginRequest)(nil), "helloworld.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "helloworld.LoginReply")
	proto.RegisterType((*ShopItemInfo)(nil), "helloworld.ShopItemInfo")
	proto.RegisterType((*EquipResp)(nil), "helloworld.EquipResp")
	proto.RegisterType((*EquipInfo)(nil), "helloworld.EquipInfo")
	proto.RegisterType((*UserRole)(nil), "helloworld.UserRole")
	proto.RegisterType((*RegisterRequest)(nil), "helloworld.RegisterRequest")
	proto.RegisterType((*RegisterReply)(nil), "helloworld.RegisterReply")
	proto.RegisterType((*Profile)(nil), "helloworld.Profile")
	proto.RegisterType((*SearchRequest)(nil), "helloworld.SearchRequest")
	proto.RegisterMapType((map[int32]*ListDate)(nil), "helloworld.SearchRequest.ListEntry")
	proto.RegisterType((*ListDate)(nil), "helloworld.ListDate")
	proto.RegisterMapType((map[int32]int32)(nil), "helloworld.ListDate.ListEntry")
}

func init() { proto.RegisterFile("pb/user.proto", fileDescriptor_c4f917211a932270) }

var fileDescriptor_c4f917211a932270 = []byte{
	// 1008 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0x35, 0xa9, 0x17, 0x79, 0x25, 0xb9, 0xc6, 0xc0, 0x49, 0x19, 0xb9, 0x6e, 0x14, 0x26, 0x0b,
	0xa1, 0x28, 0x5c, 0x54, 0x2d, 0xe0, 0x20, 0x5d, 0x14, 0x71, 0x65, 0x38, 0x02, 0x1c, 0xa3, 0x18,
	0xc7, 0xed, 0x92, 0x18, 0x8b, 0xd7, 0xf2, 0x20, 0x7c, 0x85, 0x0f, 0x2b, 0xda, 0xf5, 0x23, 0xfa,
	0x65, 0xdd, 0x74, 0xd9, 0x4f, 0x69, 0x31, 0x77, 0x48, 0x89, 0xb2, 0x95, 0x22, 0x2b, 0xcd, 0x7d,
	0xce, 0xb9, 0x67, 0xce, 0x8c, 0x08, 0xfd, 0xe4, 0xfa, 0xbb, 0x22, 0xc3, 0xf4, 0x28, 0x49, 0xe3,
	0x3c, 0x66, 0x70, 0x8b, 0x41, 0x10, 0x2f, 0xe2, 0x34, 0xf0, 0xdd, 0x17, 0xb0, 0x77, 0x95, 0x61,
	0x7a, 0xb2, 0xbc, 0x9a, 0x4e, 0x38, 0x7e, 0x28, 0x30, 0xcb, 0xd9, 0x1e, 0x34, 0x0a, 0xe9, 0x3b,
	0xc6, 0xd0, 0x18, 0xd9, 0x5c, 0x2d, 0xdd, 0x10, 0x76, 0x6b, 0x59, 0x49, 0xb0, 0x64, 0x23, 0x68,
	0xaa, 0x8e, 0x94, 0xd4, 0x1d, 0xef, 0x1f, 0xad, 0x5b, 0x1e, 0xa9, 0xcc, 0x69, 0x74, 0x13, 0x73,
	0xca, 0x60, 0xdf, 0x83, 0xad, 0x7e, 0xbd, 0x34, 0x0e, 0xd0, 0x31, 0xb7, 0xa7, 0xf3, 0x38, 0x40,
	0x6e, 0x15, 0xe5, 0xca, 0xfd, 0xdb, 0x04, 0xab, 0xea, 0xc2, 0x76, 0xc1, 0x5c, 0x81, 0x31, 0xa5,
	0xcf, 0x0e, 0xc0, 0xf6, 0xf1, 0x4e, 0xce, 0xd0, 0x93, 0x3e, 0xf5, 0xb3, 0xb9, 0xa5, 0x1d, 0x53,
	0x9f, 0xed, 0x43, 0x2b, 0xc0, 0x3b, 0x0c, 0x9c, 0xc6, 0xd0, 0x18, 0x35, 0xb9, 0x36, 0xd8, 0x63,
	0x68, 0x63, 0x84, 0xe9, 0x7c, 0xe9, 0x34, 0xc9, 0x5d, 0x5a, 0xec, 0x4b, 0xe8, 0x88, 0x24, 0xf1,
	0xd4, 0xb0, 0x2d, 0x1d, 0x10, 0x49, 0x72, 0x25, 0x7d, 0x36, 0x00, 0x2b, 0x92, 0xb3, 0xf7, 0x91,
	0x08, 0xd1, 0x69, 0xeb, 0x2d, 0x2a, 0x5b, 0x35, 0x13, 0x77, 0x22, 0x17, 0xa9, 0xd3, 0xa1, 0x48,
	0x69, 0x29, 0xd6, 0xc4, 0x1c, 0x1d, 0x6b, 0x68, 0x8c, 0x5a, 0x5c, 0x2d, 0x95, 0x27, 0xc3, 0x8f,
	0x8e, 0xad, 0x3d, 0x19, 0x7e, 0x64, 0x0e, 0x74, 0x92, 0x34, 0xbe, 0x91, 0x01, 0x3a, 0x40, 0xc5,
	0x95, 0xa9, 0x22, 0xb3, 0xb8, 0x88, 0xf2, 0x74, 0xe9, 0x74, 0x87, 0xc6, 0xa8, 0xc1, 0x2b, 0x93,
	0x31, 0x68, 0xce, 0x64, 0xbe, 0x74, 0x7a, 0x54, 0x40, 0x6b, 0x35, 0x26, 0x85, 0x9d, 0xbe, 0x1e,
	0x93, 0x0c, 0xf6, 0x0c, 0x7a, 0x11, 0x2e, 0xbc, 0x79, 0x21, 0x7d, 0x11, 0xcd, 0xd0, 0xd9, 0xa5,
	0x60, 0x37, 0xc2, 0xc5, 0x59, 0xe9, 0x72, 0xff, 0x34, 0xa1, 0x77, 0x1e, 0xcf, 0x65, 0x54, 0x9d,
	0xf5, 0x00, 0x88, 0x76, 0x9a, 0x54, 0x73, 0xbc, 0xb2, 0xd9, 0x53, 0xe8, 0xce, 0x02, 0x89, 0x51,
	0xee, 0xf9, 0x22, 0xd7, 0x67, 0xd7, 0xe4, 0xa0, 0x5d, 0x13, 0x91, 0x23, 0x3b, 0x04, 0x28, 0x8f,
	0x22, 0xc2, 0x05, 0x51, 0x6e, 0xf3, 0xf2, 0x70, 0x2e, 0x70, 0xa1, 0x7a, 0x27, 0x81, 0xc8, 0x6f,
	0xe2, 0x34, 0x24, 0xe2, 0x6d, 0xbe, 0xb2, 0xd5, 0xbc, 0x77, 0x98, 0x66, 0x32, 0x8e, 0x88, 0x7a,
	0x9b, 0x57, 0x26, 0x55, 0x89, 0x2c, 0x5b, 0xc4, 0xa9, 0x5f, 0x71, 0x5f, 0xd9, 0x8a, 0x7b, 0xdd,
	0xbe, 0xe2, 0x5e, 0x5b, 0xec, 0x05, 0xec, 0xce, 0x45, 0x88, 0xde, 0x5a, 0x18, 0x16, 0xc5, 0x7b,
	0xca, 0x3b, 0xa9, 0xc4, 0x51, 0xe3, 0xd8, 0xde, 0xe0, 0xd8, 0xfd, 0xc7, 0x00, 0x28, 0x69, 0x51,
	0xe2, 0x7e, 0x70, 0x01, 0xea, 0x4a, 0x31, 0x37, 0x94, 0xb2, 0xa1, 0xee, 0xc6, 0xe7, 0xa8, 0x9b,
	0xbd, 0x82, 0xfe, 0x02, 0x45, 0x2a, 0xa3, 0xb9, 0x87, 0x1f, 0x0a, 0x99, 0x10, 0x37, 0xdd, 0xf1,
	0xa3, 0x7a, 0xd9, 0xa9, 0x0a, 0x70, 0xcc, 0x12, 0xde, 0x2b, 0x73, 0xc9, 0xc3, 0x8e, 0x01, 0xa8,
	0xc6, 0x0b, 0x64, 0x96, 0x3b, 0xad, 0x61, 0x63, 0xd4, 0x1d, 0x3b, 0xf5, 0xc2, 0xcb, 0xdb, 0x38,
	0x99, 0xe6, 0x18, 0xd2, 0x05, 0xb4, 0x29, 0xf7, 0x5c, 0x66, 0xb9, 0xfb, 0x0e, 0x7a, 0xf5, 0x90,
	0x1a, 0x48, 0xe6, 0x18, 0x7a, 0xe5, 0x98, 0x0d, 0xde, 0x56, 0xa6, 0xbe, 0x41, 0x49, 0xaa, 0x18,
	0x36, 0xc9, 0xad, 0x0d, 0xf6, 0x08, 0xda, 0x32, 0xf3, 0xae, 0x8b, 0x25, 0xcd, 0x68, 0xf1, 0x96,
	0xcc, 0x4e, 0x8a, 0xa5, 0x7b, 0x03, 0xf6, 0x0a, 0x29, 0xfb, 0x71, 0x03, 0x9b, 0x41, 0xd8, 0x1e,
	0x0e, 0x75, 0x0f, 0x18, 0x7b, 0x0e, 0xfd, 0x24, 0x10, 0x59, 0x1e, 0x87, 0x21, 0xa6, 0xde, 0x8a,
	0xdf, 0xde, 0xda, 0x39, 0xf5, 0xdd, 0x9f, 0xcb, 0x7d, 0x08, 0xfa, 0x00, 0x2c, 0x85, 0xf5, 0xdd,
	0x32, 0xc1, 0x12, 0xfb, 0xca, 0x56, 0x02, 0xa1, 0x39, 0x26, 0x25, 0xfc, 0xd2, 0x72, 0x27, 0xfa,
	0x41, 0x21, 0xfe, 0x0f, 0x01, 0x30, 0x8c, 0x73, 0x19, 0x47, 0xd5, 0xf4, 0x4d, 0x6e, 0x97, 0x9e,
	0xa9, 0xcf, 0x9e, 0x80, 0x15, 0xc6, 0x3e, 0x06, 0x6b, 0x2c, 0x1d, 0xb2, 0xa7, 0xbe, 0xfb, 0x87,
	0x01, 0x5f, 0x70, 0x9c, 0xcb, 0x2c, 0xc7, 0xf4, 0x73, 0x2e, 0x50, 0x5d, 0xca, 0xe6, 0x3d, 0x29,
	0xd7, 0xc4, 0xd8, 0xa0, 0x07, 0x62, 0x75, 0xe1, 0x0f, 0xc0, 0x4e, 0x6e, 0xe3, 0x08, 0xbd, 0xa8,
	0x58, 0xdf, 0x1b, 0xe5, 0xb8, 0x28, 0x42, 0xf7, 0x19, 0xf4, 0xd7, 0x08, 0xb6, 0x6a, 0xd5, 0xbd,
	0x84, 0xce, 0xaf, 0xe5, 0xab, 0x72, 0x08, 0xb6, 0x0c, 0xc5, 0x1c, 0xbd, 0x22, 0x0d, 0x74, 0xca,
	0x9b, 0x1d, 0x6e, 0x91, 0xeb, 0x2a, 0x0d, 0xd8, 0x53, 0x00, 0x1d, 0xf6, 0x45, 0x2e, 0x08, 0x61,
	0xef, 0xcd, 0x0e, 0xd7, 0x25, 0x13, 0x91, 0x8b, 0x13, 0xab, 0x7a, 0xeb, 0xdc, 0x7f, 0x0d, 0xe8,
	0x5f, 0xa2, 0x48, 0x67, 0xb7, 0xd5, 0xe0, 0x2f, 0xa1, 0x3d, 0x8b, 0xd3, 0xa4, 0xc8, 0xa8, 0xf1,
	0xee, 0x78, 0xb8, 0x21, 0xc3, 0x7a, 0xea, 0xd1, 0x2f, 0x94, 0xc7, 0xcb, 0x7c, 0x76, 0x0c, 0x4d,
	0x92, 0x88, 0x49, 0x12, 0x79, 0xfe, 0xe9, 0x3a, 0x25, 0x90, 0x53, 0xc5, 0x09, 0xa7, 0x82, 0xc1,
	0x5b, 0xb0, 0x57, 0x2e, 0x35, 0xf8, 0x7b, 0x5c, 0xd2, 0xe6, 0x2d, 0xae, 0x96, 0xec, 0x1b, 0x68,
	0xdd, 0x89, 0xa0, 0xd8, 0xfa, 0x2f, 0xa3, 0xea, 0xd4, 0x9b, 0xc5, 0x75, 0xca, 0x2b, 0xf3, 0xa5,
	0xe1, 0x7e, 0x0b, 0x6d, 0x8d, 0x8c, 0xf5, 0xc1, 0xbe, 0xba, 0x98, 0xfe, 0x76, 0xca, 0x2f, 0x5f,
	0x9f, 0xef, 0xed, 0xb0, 0x0e, 0x34, 0x7e, 0x3f, 0x3d, 0xd9, 0x33, 0x18, 0x40, 0x7b, 0xfa, 0xf6,
	0xf5, 0xd9, 0xe9, 0xe5, 0x9e, 0xe9, 0x2e, 0xc0, 0xaa, 0x9a, 0xb0, 0x71, 0x39, 0x81, 0x16, 0xf9,
	0xd7, 0xdb, 0x36, 0x7a, 0x00, 0xfe, 0xf8, 0xff, 0xc1, 0xef, 0xd7, 0xc1, 0xb7, 0x6a, 0x30, 0xc7,
	0x7f, 0x19, 0xd0, 0x54, 0xe2, 0x65, 0x13, 0xb0, 0xaa, 0xb3, 0x67, 0x07, 0xf5, 0x3d, 0xef, 0x69,
	0x72, 0xf0, 0x64, 0x7b, 0x30, 0x09, 0x96, 0xee, 0x0e, 0xfb, 0x09, 0x5a, 0xf4, 0xd4, 0xb1, 0x8d,
	0x77, 0xa3, 0xfe, 0xa7, 0x30, 0x78, 0xbc, 0x25, 0xa2, 0x8b, 0xcf, 0xc0, 0x5e, 0x7d, 0x08, 0xb0,
	0xaf, 0xee, 0x3f, 0x74, 0xf5, 0xaf, 0x88, 0xc1, 0xe0, 0x13, 0x51, 0x6a, 0x74, 0xdd, 0xa6, 0x4f,
	0x91, 0x1f, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x46, 0x46, 0x06, 0xef, 0x9b, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	UserByUID(ctx context.Context, in *UserByUIDRequest, opts ...grpc.CallOption) (*UserByUIDReply, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, "/helloworld.User/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/helloworld.User/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UserByUID(ctx context.Context, in *UserByUIDRequest, opts ...grpc.CallOption) (*UserByUIDReply, error) {
	out := new(UserByUIDReply)
	err := c.cc.Invoke(ctx, "/helloworld.User/UserByUID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	UserByUID(context.Context, *UserByUIDRequest) (*UserByUIDReply, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedUserServer) Login(ctx context.Context, req *LoginRequest) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserServer) UserByUID(ctx context.Context, req *UserByUIDRequest) (*UserByUIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserByUID not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.User/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.User/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UserByUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserByUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UserByUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.User/UserByUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UserByUID(ctx, req.(*UserByUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _User_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _User_Login_Handler,
		},
		{
			MethodName: "UserByUID",
			Handler:    _User_UserByUID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/user.proto",
}
